contact.form.*.third_party.contact_scheduler:
  type: mapping
  label: 'Contact scheduler'
  mapping:
    start_date:
      type: string
      label: 'Start date'
    end_date:
      type: string
      label: 'End date'
    start_message:
      type: text
      label: 'Start date'
    end_message:
      type: text
      label: 'End date'
